
BasePlugin = require '../base_plugin.coffee'

module.exports = class ArrowSpacing extends BasePlugin

    rule_name: 'arrow_spacing'

    tokens: [ '->' ]

    lint : (token) ->
        # Throw error unless the following happens.
        #
        # We will take a look at the previous token to see
        # 1. That the token is properly spaced
        # 2. Wasn't generated by the CoffeeScript compiler
        # 3. That it is just indentation
        # 4. If the function declaration has no parameters
        # e.g. x(-> 3)
        #      x( -> 3)
        #
        # or a statement is wrapped in parentheses
        # e.g. (-> true)()
        #
        # we will accept either having a space or not having a space there.

        pp = @peek(-1)
        unless (token.spaced? or token.newLine? or @atEof()) and
               # Throw error unless the previous token...
               ((pp.spaced? or pp[0] is 'TERMINATOR') or #1
                pp.generated? or #2
                pp[0] is "INDENT" or #3
                (pp[1] is "(" and not pp.generated?)) #4
            @createLexError()
        else
            null
